### PR TITLE
[Task CS-52] Introduce recruitment chart pdf generator

### PR DESCRIPTION
**Pull request by twrdyyy**

### CODE REVIEW

**Comment by jmysliv** [comment]
@twrdyyy Can you upload some example how this generated pdf with charts looks like?

**Comment by twrdyyy** [comment]
@jmysliv Did not see your comment,
For given data:
image
image
image
Those are two of five charts

**Comment by jmysliv** [comment]
@twrdyyy tests are not passing

**Comment by twrdyyy** [comment]
@jmysliv @twistzzmc

**Review by twistzzmc — APPROVED** [review]

**Review by skusnierz — APPROVED** [review]
Good Job !!!

**Review by jmysliv — APPROVED** [review]

**Pull request merged**
